### ISSUE TITLE
Simulations (incl. `Examples.XLSXTest`) with `XLSX` do not compile on OpenModelica (v1.20, MSL4.0.0)

### ISSUE THREAD

**Issue by ppenguin** [modelica-3rdparty/ExternData#44]
When trying to simulate a basic model using `XLSXFile` under OM I get the following error:

```
XLSXTest_08bnd.c: In function 'XLSXTest_eqFunction_15':
XLSXTest_08bnd.c:60:122: error: too many arguments to function 'omc_ExternData_XLSXFile'
   60 |   (data->simulationInfo->realParameter[4]/* sumB PARAM */)  = omc_ExternData_Examples_XLSXTest_computeColSum(threadData, omc_ExternData_XLSXFile(threadData, (data->simulationInfo->stringParameter[0]/* dataSource.fileName PARAM */) , (data->simulationInfo->booleanParameter[0]/* dataSource.verboseRead PARAM */) , (data->simulationInfo->integerParameter[0]/* dataSource.detectMissingData PARAM */) , (data->simulationInfo->extObjs[0])), _OMC_LIT12, _OMC_LIT0, ((modelica_integer) 2), omc_ExternData_Functions_XLSX_getArrayRows2D(threadData, _OMC_LIT0, (data->simulationInfo->extObjs[0])));
      |                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from XLSXTest_model.h:27,
                 from XLSXTest_08bnd.c:2:
XLSXTest_functions.h:46:21: note: declared here
   46 | ExternData_XLSXFile omc_ExternData_XLSXFile (threadData_t *threadData, modelica_string omc_fileName, modelica_boolean omc_verboseRead, modelica_integer omc_detectMissingData);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option '-Wno-parentheses-equality' may have been intended to silence earlier diagnostics
make: *** [<builtin>: XLSXTest_08bnd.o] Error 1
make: *** Waiting for unfinished jobs....
Compilation process failed. Exited with code 2.
```

This occurs with the included example model `XLSXTest` and similarly with `XLSTest`.
It appears that the OMC generated function for `omc_ExternData_XLSXFile` has an additional (5th) argument `data->simulationInfo->extObjs[0]` that is not defined in the prototype.

Might this be a library compatibility issue, and is there a known fix or workaround for this?

**Comment by beutlich** [comment]
Can you please try with OMC 1.21.0-dev and report the issue to the OM devs if it still fails. Thanks.

**Comment by bilderbuchi** [comment]
On OMEdit master at least XLSXTest seems to work: https://libraries.openmodelica.org/branches/master/ExternData/ExternData.html

**Comment by beutlich** [comment]
Thanks for confirmation.
